# Generated by Django 5.0.3 on 2024-04-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTables',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=255)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='connection.databaseconnections')),
            ],
            options={
                'db_table': 'data_tables',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributes',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('is_primary_key', models.BooleanField()),
                ('is_foreign_key', models.BooleanField()),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.datatables')),
            ],
            options={
                'db_table': 'asset_attributes',
                'managed': True,
            },
        ),
    ]
