# Generated by Django 5.0.3 on 2024-04-15 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseresponsibilities',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='databaseresponsibilities',
            name='role',
        ),
        migrations.AddField(
            model_name='databaseconnections',
            name='department_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='connection.departmenttags'),
        ),
        migrations.AddField(
            model_name='databaseconnections',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='connection.roles'),
        ),
        migrations.DeleteModel(
            name='DatabaseResponsibilities',
        ),
    ]
