# Generated by Django 5.0.3 on 2024-04-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnections',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('database_name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'database_connections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabasePlatforms',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'database_platforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseResponsibilities',
            fields=[
                ('responsibility_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'database_responsibilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentTags',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'department_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseDepartments',
            fields=[
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='connection.databaseconnections')),
            ],
            options={
                'db_table': 'database_departments',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DatabaseConnection',
        ),
        migrations.DeleteModel(
            name='DatabasePlatform',
        ),
    ]
