# Generated by Django 5.0.3 on 2024-04-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_remove_databaseresponsibilities_connection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseplatforms',
            options={'managed': True},
        ),
        migrations.DeleteModel(
            name='DatabaseDepartments',
        ),
    ]
